### PR TITLE
`Explode Aar` option applies to all cases

### LINKED ISSUE #287: disabling Explore AAR still modifies AARs after downloading
disabling Explode AAR still modifies AARs after downloading in 1.2.129 (current).

to reproduce:
1. uncheck Explode AAR in options, enable verbose
2. start resolve
3. output log contains stuff about replacing applicationId (and it is actually replaced in the files)

### LINKED ISSUE #584: [Bug] disabling Explore AAR still downloads and modifies AARs
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3
  * External Dependency Manager version: 1.2.175
  * Source you installed EDM4U: .unitypackage
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: Admob
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the issue here:
Disable "Explode AARs" in Android Resolver Settings and then make Force Resolve. 
AARs are still downloaded and exploaded to the Plugins/Android folder.

### PR DESCRIPTION
**Pull request by chkuang-g**
Before this change, `Explode Aar` option in Android Resolver settings only applies when `Export Project` build setting is enabled, while Android Resolver always explode Aar libraries when the build setting is disabled.

This changes `Explode Aar` option to be applied no matter `Export Project` build setting is enabled or not. It is still recommended to enable this option for older version of Unity (5 to 2018) since certain version of Unity may generate broken Gradle project.

Fixes #584
Fixes #287

### CODE REVIEW

**Comment by chkuang-g** [comment]
@doterax
@ievgenmukhin
@wei-jiaxing 
@shefich

Please comment if you have any concern about this change.

**Review by doterax — APPROVED** [review]
Everything looks fine for me

File: source/AndroidResolver/src/GradleResolver.cs [hunk 1]
```diff
@@ -1161,7 +1161,7 @@ internal static bool SupportsAarFiles
             // To work around this when Gradle builds are enabled, explosion is enabled for all
```
Comment (a-maurice) [inline source/AndroidResolver/src/GradleResolver.cs:1161]: Update the comments for this?

**Review by a-maurice — APPROVED** [review]

File: source/AndroidResolver/src/GradleResolver.cs (hunk 1 above)
Comment (chkuang-g) [reply source/AndroidResolver/src/GradleResolver.cs:1161]: This comment is actually good with current code. It does not explicitly mention about "Gradle Project Export need to be enabled as well" part.

Comment (a-maurice) [reply source/AndroidResolver/src/GradleResolver.cs:1161]: Ah, sounds good
